package drunix

// Drunix LP/CP pipeline — faithful implementation of the Drunix architecture
// (NPCI's Hyperledger Fabric enterprise fork), in Go, as Drunix is.
//
// Transaction Flow (NPCI spec, 5 phases):
//
//	1 Endorsement   Client -> LP: chaincode execution, RW Set generation,
//	                KeyDB (transient store) storage.
//	2 Submit Txn    Client collects endorsements, signs the envelope and
//	                submits it to the Orderer.
//	3 Ordering      Orderer batches txns into blocks; CP pulls consecutive
//	                blocks.
//	4 Validation    CP -> VS (round-robin): policy check, signature verify;
//	                CP: MVCC validation.
//	5 Commit        CP commits the block to the ledger, then applies the
//	                write sets to the State DB.
//
// Drunix splits the traditional Fabric peer into two specialized roles:
//
//	Lite Peer (LP)          stateless endorser: executes chaincode, generates
//	                        the Read-Write Set, manages private data in the
//	                        transient store. No local ledger storage.
//	Orderer (RAFT)          orders endorsed envelopes; leader + followers
//	                        (simulated consensus: deterministic election).
//	Validation Service (VS) stateless, horizontally scalable: endorsement-policy
//	                        acceptance checks + cryptographic signature
//	                        verification (the VSCC role).
//	Committing Peer (CP)    MVCC validation of the RW set against current state
//	                        versions, verifies the private-data hash, applies
//	                        the write set to the State DB, commits the block.
//
// Supporting structures, per the Drunix spec:
//
//	Read-Write Set (RW Set) keys read during chaincode simulation (with the
//	                        versions seen) + keys updated during execution.
//	Transient Store (KeyDB) temporary in-memory private data shared between LP
//	                        and CP within an org. NEVER persisted to the ledger
//	                        (only its hash travels in the signed proposal and
//	                        the committed block).
//	Endorsement Policy      required set of endorsers for validity, verified by
//	                        the Validation Service.
//	MVCC Validation         multi-version concurrency control: read-write
//	                        conflicts from concurrent transactions are detected
//	                        BEFORE ledger commit (double-spend prevention).
//	State DB                YugabyteDB in production; in-memory here (mock).

import (
	"crypto/hmac"
	"crypto/sha512"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"
)

// ---------- State DB (versioned) ----------

// VersionedValue is a state entry with its monotonically increasing version.
type VersionedValue struct {
	Value   string `json:"value"`
	Version uint64 `json:"version"`
}

// StateDB is the versioned key-value store (YugabyteDB in production).
type StateDB struct {
	mu   sync.RWMutex
	data map[string]VersionedValue
}

// NewStateDB creates an empty versioned state store.
func NewStateDB() *StateDB { return &StateDB{data: map[string]VersionedValue{}} }

// GetVersion returns the current versioned value for a key (missing = version 0, empty value).
func (s *StateDB) GetVersion(key string) VersionedValue {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if v, ok := s.data[key]; ok {
		return v
	}
	return VersionedValue{Value: "", Version: 0}
}

// Apply writes a batch. Called only by the Committing Peer after MVCC passes;
// every write bumps the key's version (that is what future MVCC checks compare against).
func (s *StateDB) Apply(writes map[string]string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	for k, v := range writes {
		cur := s.data[k]
		s.data[k] = VersionedValue{Value: v, Version: cur.Version + 1}
	}
}

// Size returns the number of live keys (observability).
func (s *StateDB) Size() int { s.mu.RLock(); defer s.mu.RUnlock(); return len(s.data) }

// ---------- Read-Write Set ----------

// RWSet captures the keys read (with the versions seen) and the keys written
// during chaincode simulation. Generated by the LP; validated by the CP via MVCC.
type RWSet struct {
	Reads       map[string]uint64 `json:"reads"`       // key -> version seen during simulation
	Writes      map[string]string `json:"writes"`      // key -> new value
	ReadsOrder  []string          `json:"readsOrder"`  // arrival order (deterministic MVCC + digest)
	WritesOrder []string          `json:"writesOrder"` // arrival order (deterministic digest)
}

func (rw *RWSet) read(state *StateDB, key string) string {
	if _, seen := rw.Reads[key]; !seen {
		v := state.GetVersion(key)
		rw.Reads[key] = v.Version
		rw.ReadsOrder = append(rw.ReadsOrder, key)
	}
	return state.GetVersion(key).Value
}

func (rw *RWSet) write(key, value string) {
	if _, seen := rw.Writes[key]; !seen {
		rw.WritesOrder = append(rw.WritesOrder, key)
	}
	rw.Writes[key] = value
}

// Digest is the canonical SHA-512 of the RW set: signed by every endorser,
// verified implicitly by the CP (state changes => MVCC catches it) and
// recorded in the committed block.
func (rw *RWSet) Digest() string {
	h := sha512.New()
	rk := append([]string{}, rw.ReadsOrder...)
	sort.Strings(rk)
	for _, k := range rk {
		fmt.Fprintf(h, "R|%s|%d;", k, rw.Reads[k])
	}
	wk := append([]string{}, rw.WritesOrder...)
	sort.Strings(wk)
	for _, k := range wk {
		fmt.Fprintf(h, "W|%s|%s;", k, rw.Writes[k])
	}
	return hex.EncodeToString(h.Sum(nil))
}

// ---------- Transient Store (KeyDB) ----------

// TransientStore is the temporary in-memory private-data store shared between
// LP and CP within an org. Contents are never persisted to the ledger: the
// signed proposal and the committed block carry only a hash, and entries are
// consumed (removed) when the CP applies them.
type TransientStore struct {
	mu   sync.Mutex
	orgs map[string]map[string][]byte // org -> key -> private value
}

// NewTransientStore creates an empty KeyDB.
func NewTransientStore() *TransientStore {
	return &TransientStore{orgs: map[string]map[string][]byte{}}
}

// Put stores private data (LP side).
func (t *TransientStore) Put(org, key string, val []byte) {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.orgs[org] == nil {
		t.orgs[org] = map[string][]byte{}
	}
	t.orgs[org][key] = val
}

// Take reads and removes private data (CP side — consumed, not kept).
func (t *TransientStore) Take(org, key string) ([]byte, bool) {
	t.mu.Lock()
	defer t.mu.Unlock()
	m, ok := t.orgs[org]
	if !ok {
		return nil, false
	}
	v, ok := m[key]
	delete(m, key)
	return v, ok
}

// Size reports live private-data entries across orgs (observability).
func (t *TransientStore) Size() int {
	t.mu.Lock()
	defer t.mu.Unlock()
	n := 0
	for _, m := range t.orgs {
		n += len(m)
	}
	return n
}

// ---------- Endorsements + policy (simulated PKI) ----------

// Endorsement is one peer's signature over the transaction proposal.
type Endorsement struct {
	MSP       string `json:"msp"`
	Peer      string `json:"peer"`
	Signature string `json:"signature"` // HMAC-SHA512 (simulated PKI; real Drunix uses MSP X.509)
}

// EndorsementPolicy is the required set of endorsers (AND semantics).
type EndorsementPolicy struct {
	RequiredMSPs []string `json:"requiredMSPs"`
}

// orgKey derives the per-org signing key. Only key holders can produce valid
// endorsements — same verification semantics as MSP certificate checks.
func orgKey(msp string) []byte {
	sum := sha512.Sum512([]byte("drunix-org-signing-key|" + msp))
	return sum[:]
}

func signProposal(msp, proposal string) string {
	mac := hmac.New(sha512.New, orgKey(msp))
	mac.Write([]byte(proposal))
	return hex.EncodeToString(mac.Sum(nil))
}

func verifyEndorsement(e Endorsement, proposal string) bool {
	return hmac.Equal([]byte(signProposal(e.MSP, proposal)), []byte(e.Signature))
}

// SatisfiedBy verifies every endorsement's signature and AND-coverage.
func (p EndorsementPolicy) SatisfiedBy(proposal string, endorsements []Endorsement) (bool, string) {
	byMSP := map[string]bool{}
	for _, e := range endorsements {
		if !verifyEndorsement(e, proposal) {
			return false, fmt.Sprintf("invalid signature from %s (%s) — proposal was modified after endorsement", e.MSP, e.Peer)
		}
		byMSP[e.MSP] = true
	}
	for _, m := range p.RequiredMSPs {
		if !byMSP[m] {
			return false, fmt.Sprintf("endorsement policy AND(%s) not satisfied: missing %s", strings.Join(p.RequiredMSPs, ","), m)
		}
	}
	return true, ""
}

// ---------- Chaincode (aasthi) — policies + simulation ----------

// policyFor returns the endorsement policy per chaincode function.
func policyFor(fn string) EndorsementPolicy {
	// Money-leg functions carry their own policies (see cash.go): the payment
	// operator signs cash movements, and DvP additionally requires the
	// platform, so neither organisation can move the other's asset alone.
	if p, owned := cashPolicyFor(fn); owned {
		return p
	}
	switch fn {
	case "MintPropertyTokens":
		return EndorsementPolicy{RequiredMSPs: []string{"OriginatorMSP", "RegistrarMSP"}}
	case "FreezeProperty":
		return EndorsementPolicy{RequiredMSPs: []string{"RegulatorMSP"}}
	default: // TransferTokens, DistributeYield, ...
		return EndorsementPolicy{RequiredMSPs: []string{"AasthiChainMSP", "InvestorMSP"}}
	}
}

// simulateChaincode executes fn against the state and produces the RW set.
// Balances are stored as decimal strings under balance~<assetId>~<owner>.
func simulateChaincode(state *StateDB, fn string, args []string, rw *RWSet) error {
	parseInt := func(s string) (uint64, error) {
		var n uint64
		if _, err := fmt.Sscanf(s, "%d", &n); err != nil {
			return 0, fmt.Errorf("invalid number %q", s)
		}
		return n, nil
	}
	// Cash and DvP functions live in cash.go. They share this RW set, which is
	// what lets SettleDvP put the money leg and the securities leg into one
	// transaction rather than two sequential ledger appends.
	if handled, err := simulateCashChaincode(state, fn, args, rw); handled {
		return err
	}
	switch fn {
	case "MintPropertyTokens": // args: assetId, owner, total
		if len(args) < 3 {
			return fmt.Errorf("MintPropertyTokens needs assetId, owner, total")
		}
		total, err := parseInt(args[2])
		if err != nil {
			return err
		}
		_ = total
		rw.read(state, "property~"+args[0])
		rw.write("property~"+args[0], "TOKENIZED")
		rw.write("balance~"+args[0]+"~"+args[1], args[2])
	case "TransferTokens": // args: assetId, from, to, amount
		if len(args) < 4 {
			return fmt.Errorf("TransferTokens needs assetId, from, to, amount")
		}
		amt, err := parseInt(args[3])
		if err != nil {
			return err
		}
		fromKey, toKey := "balance~"+args[0]+"~"+args[1], "balance~"+args[0]+"~"+args[2]
		fromStr := rw.read(state, fromKey)
		bal, err := parseInt(fromStr)
		if err != nil {
			bal = 0 // zero balance = empty key
		}
		if bal < amt {
			return fmt.Errorf("insufficient balance: have %d need %d (double-spend stopped at endorsement)", bal, amt)
		}
		toStr := rw.read(state, toKey)
		toBal, err := parseInt(toStr)
		if err != nil {
			toBal = 0
		}
		rw.write(fromKey, fmt.Sprint(bal-amt))
		rw.write(toKey, fmt.Sprint(toBal+amt))
	case "DistributeYield": // args: assetId, amountINR
		if len(args) < 2 {
			return fmt.Errorf("DistributeYield needs assetId, amountINR")
		}
		if _, err := parseInt(args[1]); err != nil {
			return err
		}
		rw.read(state, "property~"+args[0])
		rw.write("yield~"+args[0]+"~"+fmt.Sprint(time.Now().UnixNano()), args[1])
	case "FreezeProperty": // args: assetId
		if len(args) < 1 {
			return fmt.Errorf("FreezeProperty needs assetId")
		}
		rw.read(state, "property~"+args[0])
		rw.write("property~"+args[0], "FROZEN")
	default:
		return fmt.Errorf("unknown chaincode function %q", fn)
	}
	return nil
}

// ---------- Lite Peer (LP) ----------

// PrivateRef locates one private-data entry in the transient store.
type PrivateRef struct {
	Org string `json:"org"`
	Key string `json:"key"`
}

// LitePeer is the stateless endorsing peer: executes chaincode, generates the
// RW set, writes private data into the transient store. No local ledger.
type LitePeer struct {
	State     *StateDB        // read-only view during simulation
	Transient *TransientStore // KeyDB hand-off to the CP
}

// Endorse executes chaincode and returns the signed proposal, RW set,
// endorsements and the transient-store references for the private data.
func (lp *LitePeer) Endorse(fn string, args []string, private map[string]map[string][]byte) (proposal string, rw *RWSet, endorsements []Endorsement, refs []PrivateRef, privateDigest string, err error) {
	rw = &RWSet{Reads: map[string]uint64{}, Writes: map[string]string{}}
	if err = simulateChaincode(lp.State, fn, args, rw); err != nil {
		return "", nil, nil, nil, "", err
	}

	// Private data → transient store (KeyDB). The proposal carries only the
	// hash of the private payload (Fabric collection-hash semantics).
	ph := sha512.New()
	orgs := make([]string, 0, len(private))
	for org := range private {
		orgs = append(orgs, org)
	}
	sort.Strings(orgs)
	for _, org := range orgs {
		fields := make([]string, 0, len(private[org]))
		field := map[string][]byte{}
		for f, v := range private[org] {
			fields = append(fields, f)
			field[f] = v
		}
		sort.Strings(fields)
		for _, f := range fields {
			key := "pv|" + org + "|" + fn + "|" + f
			lp.Transient.Put(org, key, private[org][f])
			refs = append(refs, PrivateRef{Org: org, Key: key})
			fmt.Fprintf(ph, "%s|%s|%s;", org, key, private[org][f])
		}
	}
	privateDigest = hex.EncodeToString(ph.Sum(nil))

	// proposal = channel|chaincode|fn|args|rwDigest|privateDigest
	proposal = strings.Join([]string{Channel, ChaincodeName, fn, strings.Join(args, "\x1f"), rw.Digest(), privateDigest}, "|")
	for _, msp := range policyFor(fn).RequiredMSPs {
		endorsements = append(endorsements, Endorsement{MSP: msp, Peer: msp + ".peer", Signature: signProposal(msp, proposal)})
	}
	return proposal, rw, endorsements, refs, privateDigest, nil
}

// ---------- Client (Phase 2: collects endorsements, signs, submits) ----------

// Envelope is what the client hands to the Orderer: the endorsed proposal
// (with its RW set and endorsements) plus the client's own signature.
type Envelope struct {
	TxID          string        `json:"txId"`
	Fn            string        `json:"fn"`
	Args          []string      `json:"args"`
	Proposal      string        `json:"proposal"`
	RW            *RWSet        `json:"rwSet"`
	RWDigest      string        `json:"rwDigest"`
	PrivateDigest string        `json:"privateDigest,omitempty"`
	PrivateRefs   []PrivateRef  `json:"privateRefs,omitempty"`
	Endorsements  []Endorsement `json:"endorsements"`
	ClientID      string        `json:"clientId"`
	ClientSig     string        `json:"clientSig"`
	Seq           uint64        `json:"seq"`
	Leader        int           `json:"leader"`
}

// clientKey derives a client signing key (simulated PKI; stateless verify).
func clientKey(id string) []byte {
	sum := sha512.Sum512([]byte("drunix-client-signing-key|" + id))
	return sum[:]
}

func signEnvelope(id, proposal string) string {
	mac := hmac.New(sha512.New, clientKey(id))
	mac.Write([]byte(proposal))
	return hex.EncodeToString(mac.Sum(nil))
}

// verifyClientSig re-derives the key from the envelope's client ID, so any
// stateless VS instance can check it.
func verifyClientSig(env *Envelope) bool {
	return hmac.Equal([]byte(signEnvelope(env.ClientID, env.Proposal)), []byte(env.ClientSig))
}

// Client is the transaction submitter (the DLT-Gateway signs on the user's
// behalf). Phase 2: collect endorsements, sign the envelope, submit to Orderer.
type Client struct{ ID string }

// NewClient creates a client identity.
func NewClient(id string) *Client { return &Client{ID: id} }

// Sign builds the signed envelope (Phase 2 of the transaction flow).
func (c *Client) Sign(fn string, args []string, proposal string, rw *RWSet, endorsements []Endorsement, refs []PrivateRef, privateDigest string) *Envelope {
	return &Envelope{
		Fn: fn, Args: args, Proposal: proposal, RW: rw, RWDigest: rw.Digest(),
		PrivateDigest: privateDigest, PrivateRefs: refs, Endorsements: endorsements,
		ClientID: c.ID, ClientSig: signEnvelope(c.ID, proposal),
	}
}

// ---------- Orderer (Phase 3: RAFT, batches txns into blocks) ----------

// OrderedBlock is a batch of ordered envelopes cut by the Orderer; the CP
// pulls these consecutively.
type OrderedBlock struct {
	Seq       uint64      `json:"seq"`
	Leader    int         `json:"leader"`
	Nodes     int         `json:"nodes"`
	Envelopes []*Envelope `json:"envelopes"`
}

// Orderer stamps each envelope with cluster-unique sequence + leader (Raft
// simulated: deterministic election) and batches them into blocks. Real
// Drunix runs Raft.
type Orderer struct {
	Nodes    int
	BatchMax int // max txns per block
	Seq      uint64

	mu      sync.Mutex
	pending []*Envelope
	blocks  map[uint64]*OrderedBlock
	cut     uint64
}

// NewOrderer creates a cluster of n orderers with a default batch size of 4.
func NewOrderer(n int) *Orderer {
	return &Orderer{Nodes: n, BatchMax: 4, blocks: map[uint64]*OrderedBlock{}}
}

// Leader returns the current Raft leader (1-based).
func (o *Orderer) Leader() int { return int(((o.Seq + uint64(o.Nodes) - 1) % uint64(o.Nodes)) + 1) }

// Submit stamps the envelope (sequence, leader, deterministic txID) and adds
// it to the pending batch.
func (o *Orderer) Submit(env *Envelope) (seq uint64, leader int) {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.Seq++
	env.Seq, env.Leader = o.Seq, o.Leader()
	env.TxID = mockTxID(Channel, ChaincodeName, env.Fn, env.Args, env.Seq)
	o.pending = append(o.pending, env)
	return env.Seq, env.Leader
}

// Full reports whether the pending batch reached BatchMax (auto-cut point).
func (o *Orderer) Full() bool {
	o.mu.Lock()
	defer o.mu.Unlock()
	return len(o.pending) >= o.BatchMax
}

// Cut drains the pending batch into one ordered block.
func (o *Orderer) Cut() *OrderedBlock {
	o.mu.Lock()
	defer o.mu.Unlock()
	if len(o.pending) == 0 {
		return nil
	}
	o.cut++
	blk := &OrderedBlock{Seq: o.cut, Leader: o.Leader(), Nodes: o.Nodes, Envelopes: o.pending}
	o.blocks[o.cut] = blk
	o.pending = nil
	return blk
}

// Block returns the ordered block with the given sequence (CP pull path).
func (o *Orderer) Block(n uint64) (*OrderedBlock, bool) {
	o.mu.Lock()
	defer o.mu.Unlock()
	blk, ok := o.blocks[n]
	return blk, ok
}

// Pending reports how many txns sit in the un-cut batch (observability).
func (o *Orderer) Pending() int { o.mu.Lock(); defer o.mu.Unlock(); return len(o.pending) }

// BlocksCut reports how many ordered blocks exist (observability).
func (o *Orderer) BlocksCut() uint64 { o.mu.Lock(); defer o.mu.Unlock(); return o.cut }

// ---------- Validation Service (Phase 4: VS / VSCC, round-robin pool) ----------

// ValidationService is stateless and horizontally scalable: client-signature
// check, endorsement-policy acceptance, endorsement signature verification.
type ValidationService struct{}

// Validate runs the full VSCC check on a signed envelope.
func (vs *ValidationService) Validate(env *Envelope) error {
	if !verifyClientSig(env) {
		return fmt.Errorf("VSCC: invalid client signature from %s (envelope modified after client signing)", env.ClientID)
	}
	if ok, reason := policyFor(env.Fn).SatisfiedBy(env.Proposal, env.Endorsements); !ok {
		return fmt.Errorf("VSCC: %s", reason)
	}
	return nil
}

// ValidationPool is a pool of stateless VS instances; the CP dispatches to
// them round-robin (Phase 4: "CP -> VS (round-robin)").
type ValidationPool struct {
	Names     []string
	Instances []*ValidationService

	next uint64
	mu   sync.Mutex
}

// NewValidationPool creates n VS instances (vs-1 .. vs-n).
func NewValidationPool(n int) *ValidationPool {
	vp := &ValidationPool{}
	for i := 1; i <= n; i++ {
		vp.Names = append(vp.Names, fmt.Sprintf("vs-%d", i))
		vp.Instances = append(vp.Instances, &ValidationService{})
	}
	return vp
}

// Validate dispatches to the next VS instance (round-robin) and returns which
// node ran the check.
func (vp *ValidationPool) Validate(env *Envelope) (string, error) {
	vp.mu.Lock()
	i := int(vp.next % uint64(len(vp.Instances)))
	vp.next++
	vp.mu.Unlock()
	return vp.Names[i], vp.Instances[i].Validate(env)
}

// ---------- Committing Peer (Phases 4-5: MVCC, then block commit) ----------

// TxOutcome is the per-transaction result of processing an ordered block.
type TxOutcome struct {
	Env         *Envelope
	Committed   bool
	Stage       string // validation-service | committing-peer-mvcc | committing-peer-private | committed
	Reason      string
	VSNode      string
	BlockHeight int64
}

// CommittingPeer pulls consecutive ordered blocks, validates every txn
// (VS round-robin, MVCC), then commits the block to the ledger and applies
// the write sets to the State DB.
type CommittingPeer struct {
	State     *StateDB
	Transient *TransientStore
	Ledger    *DrunixChain
	VS        *ValidationPool
	Ord       *Orderer

	nextBlock uint64
	mu        sync.Mutex
}

// PullNext fetches the next consecutive ordered block (Phase 3 pull path).
func (cp *CommittingPeer) PullNext() *OrderedBlock {
	cp.mu.Lock()
	defer cp.mu.Unlock()
	blk, ok := cp.Ord.Block(cp.nextBlock + 1)
	if !ok {
		return nil
	}
	cp.nextBlock++
	return blk
}

// mvccValidate: every key read during simulation must still sit at the
// version the transaction saw. overlay carries same-block writes from
// earlier valid txns (Fabric marks the second conflicting txn in a block invalid).
func (cp *CommittingPeer) mvccValidate(rw *RWSet, overlay map[string]uint64) (bool, string) {
	for _, k := range rw.ReadsOrder {
		cur, inOverlay := overlay[k]
		if !inOverlay {
			cur = cp.State.GetVersion(k).Version
		}
		if rw.Reads[k] != cur {
			return false, fmt.Sprintf("MVCC READ_CONFLICT on %s: simulated version %d, current version %d. Resubmit with fresh state.", k, rw.Reads[k], cur)
		}
	}
	return true, ""
}

// verifyPrivate pulls the private data from the transient store and checks it
// against the hash inside the endorsed proposal.
func (cp *CommittingPeer) verifyPrivate(env *Envelope) error {
	ph := sha512.New()
	for _, ref := range env.PrivateRefs {
		val, ok := cp.Transient.Take(ref.Org, ref.Key)
		if !ok {
			return fmt.Errorf("private data %s (org %s) missing from transient store", ref.Key, ref.Org)
		}
		fmt.Fprintf(ph, "%s|%s|%s;", ref.Org, ref.Key, val)
	}
	if len(env.PrivateRefs) > 0 && hex.EncodeToString(ph.Sum(nil)) != env.PrivateDigest {
		return fmt.Errorf("private data hash mismatch against endorsed proposal")
	}
	return nil
}

// ProcessBlock runs Phase 4 (validation) for every envelope, then Phase 5
// (commit): the block goes to the ledger FIRST, write sets hit the State DB
// after — exactly the Drunix commit semantics.
func (cp *CommittingPeer) ProcessBlock(blk *OrderedBlock) map[*Envelope]*TxOutcome {
	out := map[*Envelope]*TxOutcome{}
	overlay := map[string]uint64{}
	var valid []*Envelope

	// Phase 4 — CP -> VS (round-robin) + CP MVCC validation
	for _, env := range blk.Envelopes {
		oc := &TxOutcome{Env: env}
		out[env] = oc
		node, err := cp.VS.Validate(env)
		oc.VSNode = node
		if err != nil {
			oc.Stage, oc.Reason = "validation-service", err.Error()
			continue
		}
		if ok, reason := cp.mvccValidate(env.RW, overlay); !ok {
			oc.Stage, oc.Reason = "committing-peer-mvcc", reason
			continue
		}
		if err := cp.verifyPrivate(env); err != nil {
			oc.Stage, oc.Reason = "committing-peer-private", err.Error()
			continue
		}
		for k := range env.RW.Writes {
			overlay[k] = cp.State.GetVersion(k).Version + 1
		}
		valid = append(valid, env)
	}

	// Phase 5 — commit block to ledger, THEN apply write sets to State DB
	if len(valid) > 0 {
		txns := []map[string]interface{}{}
		for _, env := range valid {
			endorsedBy := []string{}
			for _, e := range env.Endorsements {
				endorsedBy = append(endorsedBy, e.MSP)
			}
			txns = append(txns, map[string]interface{}{
				"kind":       "pipeline",
				"txId":       env.TxID,
				"chaincode":  ChaincodeName,
				"fn":         env.Fn,
				"args":       env.Args,
				"rwDigest":   env.RWDigest,
				"endorsedBy": endorsedBy,
				"orderer":    fmt.Sprintf("raft-leader-%d-of-%d", blk.Leader, blk.Nodes),
				"vs":         out[env].VSNode,
				"client":     env.ClientID,
				"mvcc":       "validated",
				"vscc":       "policy-accepted",
			})
		}
		ledgerBlk := cp.Ledger.Append("TX_COMMITTED", txns)
		for _, env := range valid {
			cp.State.Apply(env.RW.Writes)
			out[env].Committed = true
			out[env].Stage = "committed"
			out[env].BlockHeight = ledgerBlk.Height
		}
	}
	return out
}

// ---------- Pipeline: Client -> DLT-Gateway -> LP -> Orderer -> VS -> CP ----------

// CommitResult reports one pipeline run stage by stage (judge-readable).
type CommitResult struct {
	TxID          string   `json:"txId"`
	Fn            string   `json:"fn"`
	Committed     bool     `json:"committed"`
	BlockHeight   int64    `json:"blockHeight,omitempty"`
	BlockSeq      uint64   `json:"blockSeq,omitempty"`
	Stage         string   `json:"stage"` // lite-peer | ordered | validation-service | committing-peer-mvcc | committing-peer-private | committed
	Reason        string   `json:"reason,omitempty"`
	OrdererLeader int      `json:"ordererLeader"`
	Seq           uint64   `json:"seq"`
	VSNode        string   `json:"vsNode,omitempty"`
	RWDigest      string   `json:"rwDigest"`
	PrivateHash   string   `json:"privateHash,omitempty"`
	EndorsedBy    []string `json:"endorsedBy"`
	Phases        []string `json:"phases"` // completed phases of the 5-phase flow
	DurationMs    int64    `json:"durationMs"`
}

// Pipeline is the full Drunix transaction path, wired once and reused.
type Pipeline struct {
	Client *Client
	LP     *LitePeer
	Order  *Orderer
	VS     *ValidationPool
	CP     *CommittingPeer
	mu     sync.Mutex // serializes simulation/commit on the single-channel demo
}

// NewPipeline wires the components over shared state, transient store and ledger.
func NewPipeline(state *StateDB, transient *TransientStore, ledger *DrunixChain) *Pipeline {
	vs := NewValidationPool(2)
	orderer := NewOrderer(3)
	cp := &CommittingPeer{State: state, Transient: transient, Ledger: ledger, VS: vs, Ord: orderer}
	return &Pipeline{
		Client: NewClient("aasthi-gateway"),
		LP:     &LitePeer{State: state, Transient: transient},
		Order:  orderer,
		VS:     vs,
		CP:     cp,
	}
}

// Submit runs the full 5-phase lifecycle synchronously:
// 1 endorse (LP) -> 2 client signs -> 3 order (batch cut) -> 4 validate (VS
// round-robin + MVCC) -> 5 commit (ledger, then State DB). privateData maps
// org -> field -> value and travels only through the transient store.
func (p *Pipeline) Submit(fn string, args []string, private map[string]map[string][]byte) (CommitResult, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.submit(fn, args, private, false)
}

// SubmitBuffered runs phases 1-3 WITHOUT cutting a block: the txn waits in
// the orderer batch and commits together with the next flush (or when the
// batch fills) — the Drunix "Orderer batches txns into blocks" behavior.
func (p *Pipeline) SubmitBuffered(fn string, args []string, private map[string]map[string][]byte) (CommitResult, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.submit(fn, args, private, true)
}

// Flush cuts the pending batch into one ordered block and processes every
// block the CP has not pulled yet. Returns the number of committed txns.
func (p *Pipeline) Flush() int {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.flush()
}

func (p *Pipeline) submit(fn string, args []string, private map[string]map[string][]byte, buffered bool) (CommitResult, error) {
	start := time.Now()
	res := CommitResult{Fn: fn}
	finish := func(err error) (CommitResult, error) {
		res.DurationMs = time.Since(start).Milliseconds()
		return res, err
	}

	// Phase 1 — Endorsement: Client -> LP (chaincode execution, RW Set, KeyDB)
	proposal, rw, endorsements, refs, privateDigest, err := p.LP.Endorse(fn, args, private)
	if err != nil {
		res.Stage, res.Reason = "lite-peer", err.Error()
		return finish(err)
	}
	res.RWDigest, res.PrivateHash = rw.Digest(), privateDigest
	for _, e := range endorsements {
		res.EndorsedBy = append(res.EndorsedBy, e.MSP)
	}
	res.Phases = []string{"1-endorsed"}

	// Phase 2 — Submit Txn: client collects endorsements, signs the envelope
	env := p.Client.Sign(fn, args, proposal, rw, endorsements, refs, privateDigest)
	res.Phases = append(res.Phases, "2-signed")

	// Phase 3 — Ordering: orderer stamps + batches; CP pulls consecutive blocks
	p.Order.Submit(env)
	res.TxID = env.TxID
	res.Seq, res.OrdererLeader = env.Seq, env.Leader
	res.Phases = append(res.Phases, "3-ordered")

	if buffered && !p.Order.Full() {
		res.Stage = "ordered" // waiting in the batch; Flush commits it
		return finish(nil)
	}
	p.Order.Cut() // synchronous demo path: flush the batch into a block now

	var oc *TxOutcome
	var blockSeq uint64
	for b := p.CP.PullNext(); b != nil; b = p.CP.PullNext() {
		blockSeq = b.Seq
		for e, o := range p.CP.ProcessBlock(b) {
			if e == env {
				oc = o
			}
		}
	}
	if oc == nil {
		res.Stage, res.Reason = "committing-peer", "no outcome for envelope"
		return finish(fmt.Errorf("no outcome for envelope"))
	}
	res.BlockSeq, res.VSNode = blockSeq, oc.VSNode
	res.BlockHeight, res.Stage, res.Reason = oc.BlockHeight, oc.Stage, oc.Reason
	if !oc.Committed {
		return finish(fmt.Errorf("%s: %s", oc.Stage, oc.Reason))
	}
	res.Committed = true
	res.Phases = append(res.Phases, "4-validated", "5-committed")
	return finish(nil)
}

func (p *Pipeline) flush() int {
	committed := 0
	p.Order.Cut() // drain the pending batch into an ordered block
	for b := p.CP.PullNext(); b != nil; b = p.CP.PullNext() {
		for _, oc := range p.CP.ProcessBlock(b) {
			if oc.Committed {
				committed++
			}
		}
	}
	return committed
}
