package drunix

// Drunix LP/CP pipeline — faithful implementation of the Drunix architecture
// (NPCI's Hyperledger Fabric enterprise fork), in Go, as Drunix is.
//
// Drunix splits the traditional Fabric peer into two specialized roles:
//
//	Lite Peer (LP)          stateless endorser: executes chaincode, generates
//	                        the Read-Write Set, manages private data in the
//	                        transient store. No local ledger storage.
//	Orderer (RAFT)          orders endorsed envelopes; leader + followers
//	                        (simulated consensus: deterministic election).
//	Validation Service (VS) stateless, horizontally scalable: endorsement-policy
//	                        acceptance checks + cryptographic signature
//	                        verification (the VSCC role).
//	Committing Peer (CP)    MVCC validation of the RW set against current state
//	                        versions, verifies the private-data hash, applies
//	                        the write set to the State DB, commits the block.
//
// Supporting structures, per the Drunix spec:
//
//	Read-Write Set (RW Set) keys read during chaincode simulation (with the
//	                        versions seen) + keys updated during execution.
//	Transient Store (KeyDB) temporary in-memory private data shared between LP
//	                        and CP within an org. NEVER persisted to the ledger
//	                        (only its hash travels in the signed proposal and
//	                        the committed block).
//	Endorsement Policy      required set of endorsers for validity, verified by
//	                        the Validation Service.
//	MVCC Validation         multi-version concurrency control: read-write
//	                        conflicts from concurrent transactions are detected
//	                        BEFORE ledger commit (double-spend prevention).
//	State DB                YugabyteDB in production; in-memory here (mock).

import (
	"crypto/hmac"
	"crypto/sha512"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"
)

// ---------- State DB (versioned) ----------

// VersionedValue is a state entry with its monotonically increasing version.
type VersionedValue struct {
	Value   string `json:"value"`
	Version uint64 `json:"version"`
}

// StateDB is the versioned key-value store (YugabyteDB in production).
type StateDB struct {
	mu   sync.RWMutex
	data map[string]VersionedValue
}

// NewStateDB creates an empty versioned state store.
func NewStateDB() *StateDB { return &StateDB{data: map[string]VersionedValue{}} }

// GetVersion returns the current versioned value for a key (missing = version 0, empty value).
func (s *StateDB) GetVersion(key string) VersionedValue {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if v, ok := s.data[key]; ok {
		return v
	}
	return VersionedValue{Value: "", Version: 0}
}

// Apply writes a batch. Called only by the Committing Peer after MVCC passes;
// every write bumps the key's version (that is what future MVCC checks compare against).
func (s *StateDB) Apply(writes map[string]string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	for k, v := range writes {
		cur := s.data[k]
		s.data[k] = VersionedValue{Value: v, Version: cur.Version + 1}
	}
}

// Size returns the number of live keys (observability).
func (s *StateDB) Size() int { s.mu.RLock(); defer s.mu.RUnlock(); return len(s.data) }

// ---------- Read-Write Set ----------

// RWSet captures the keys read (with the versions seen) and the keys written
// during chaincode simulation. Generated by the LP; validated by the CP via MVCC.
type RWSet struct {
	Reads       map[string]uint64 `json:"reads"`       // key -> version seen during simulation
	Writes      map[string]string `json:"writes"`      // key -> new value
	ReadsOrder  []string          `json:"readsOrder"`  // arrival order (deterministic MVCC + digest)
	WritesOrder []string          `json:"writesOrder"` // arrival order (deterministic digest)
}

func (rw *RWSet) read(state *StateDB, key string) string {
	if _, seen := rw.Reads[key]; !seen {
		v := state.GetVersion(key)
		rw.Reads[key] = v.Version
		rw.ReadsOrder = append(rw.ReadsOrder, key)
	}
	return state.GetVersion(key).Value
}

func (rw *RWSet) write(key, value string) {
	if _, seen := rw.Writes[key]; !seen {
		rw.WritesOrder = append(rw.WritesOrder, key)
	}
	rw.Writes[key] = value
}

// Digest is the canonical SHA-512 of the RW set: signed by every endorser,
// verified implicitly by the CP (state changes => MVCC catches it) and
// recorded in the committed block.
func (rw *RWSet) Digest() string {
	h := sha512.New()
	rk := append([]string{}, rw.ReadsOrder...)
	sort.Strings(rk)
	for _, k := range rk {
		fmt.Fprintf(h, "R|%s|%d;", k, rw.Reads[k])
	}
	wk := append([]string{}, rw.WritesOrder...)
	sort.Strings(wk)
	for _, k := range wk {
		fmt.Fprintf(h, "W|%s|%s;", k, rw.Writes[k])
	}
	return hex.EncodeToString(h.Sum(nil))
}

// ---------- Transient Store (KeyDB) ----------

// TransientStore is the temporary in-memory private-data store shared between
// LP and CP within an org. Contents are never persisted to the ledger: the
// signed proposal and the committed block carry only a hash, and entries are
// consumed (removed) when the CP applies them.
type TransientStore struct {
	mu   sync.Mutex
	orgs map[string]map[string][]byte // org -> key -> private value
}

// NewTransientStore creates an empty KeyDB.
func NewTransientStore() *TransientStore {
	return &TransientStore{orgs: map[string]map[string][]byte{}}
}

// Put stores private data (LP side).
func (t *TransientStore) Put(org, key string, val []byte) {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.orgs[org] == nil {
		t.orgs[org] = map[string][]byte{}
	}
	t.orgs[org][key] = val
}

// Take reads and removes private data (CP side — consumed, not kept).
func (t *TransientStore) Take(org, key string) ([]byte, bool) {
	t.mu.Lock()
	defer t.mu.Unlock()
	m, ok := t.orgs[org]
	if !ok {
		return nil, false
	}
	v, ok := m[key]
	delete(m, key)
	return v, ok
}

// Size reports live private-data entries across orgs (observability).
func (t *TransientStore) Size() int {
	t.mu.Lock()
	defer t.mu.Unlock()
	n := 0
	for _, m := range t.orgs {
		n += len(m)
	}
	return n
}

// ---------- Endorsements + policy (simulated PKI) ----------

// Endorsement is one peer's signature over the transaction proposal.
type Endorsement struct {
	MSP       string `json:"msp"`
	Peer      string `json:"peer"`
	Signature string `json:"signature"` // HMAC-SHA512 (simulated PKI; real Drunix uses MSP X.509)
}

// EndorsementPolicy is the required set of endorsers (AND semantics).
type EndorsementPolicy struct {
	RequiredMSPs []string `json:"requiredMSPs"`
}

// orgKey derives the per-org signing key. Only key holders can produce valid
// endorsements — same verification semantics as MSP certificate checks.
func orgKey(msp string) []byte {
	sum := sha512.Sum512([]byte("drunix-org-signing-key|" + msp))
	return sum[:]
}

func signProposal(msp, proposal string) string {
	mac := hmac.New(sha512.New, orgKey(msp))
	mac.Write([]byte(proposal))
	return hex.EncodeToString(mac.Sum(nil))
}

func verifyEndorsement(e Endorsement, proposal string) bool {
	return hmac.Equal([]byte(signProposal(e.MSP, proposal)), []byte(e.Signature))
}

// SatisfiedBy verifies every endorsement's signature and AND-coverage.
func (p EndorsementPolicy) SatisfiedBy(proposal string, endorsements []Endorsement) (bool, string) {
	byMSP := map[string]bool{}
	for _, e := range endorsements {
		if !verifyEndorsement(e, proposal) {
			return false, fmt.Sprintf("invalid signature from %s (%s) — proposal was modified after endorsement", e.MSP, e.Peer)
		}
		byMSP[e.MSP] = true
	}
	for _, m := range p.RequiredMSPs {
		if !byMSP[m] {
			return false, fmt.Sprintf("endorsement policy AND(%s) not satisfied: missing %s", strings.Join(p.RequiredMSPs, ","), m)
		}
	}
	return true, ""
}

// ---------- Chaincode (aasthi) — policies + simulation ----------

// policyFor returns the endorsement policy per chaincode function.
func policyFor(fn string) EndorsementPolicy {
	switch fn {
	case "MintPropertyTokens":
		return EndorsementPolicy{RequiredMSPs: []string{"OriginatorMSP", "RegistrarMSP"}}
	case "FreezeProperty":
		return EndorsementPolicy{RequiredMSPs: []string{"RegulatorMSP"}}
	default: // TransferTokens, DistributeYield, ...
		return EndorsementPolicy{RequiredMSPs: []string{"AasthiChainMSP", "InvestorMSP"}}
	}
}

// simulateChaincode executes fn against the state and produces the RW set.
// Balances are stored as decimal strings under balance~<assetId>~<owner>.
func simulateChaincode(state *StateDB, fn string, args []string, rw *RWSet) error {
	parseInt := func(s string) (uint64, error) {
		var n uint64
		if _, err := fmt.Sscanf(s, "%d", &n); err != nil {
			return 0, fmt.Errorf("invalid number %q", s)
		}
		return n, nil
	}
	switch fn {
	case "MintPropertyTokens": // args: assetId, owner, total
		if len(args) < 3 {
			return fmt.Errorf("MintPropertyTokens needs assetId, owner, total")
		}
		total, err := parseInt(args[2])
		if err != nil {
			return err
		}
		_ = total
		rw.read(state, "property~"+args[0])
		rw.write("property~"+args[0], "TOKENIZED")
		rw.write("balance~"+args[0]+"~"+args[1], args[2])
	case "TransferTokens": // args: assetId, from, to, amount
		if len(args) < 4 {
			return fmt.Errorf("TransferTokens needs assetId, from, to, amount")
		}
		amt, err := parseInt(args[3])
		if err != nil {
			return err
		}
		fromKey, toKey := "balance~"+args[0]+"~"+args[1], "balance~"+args[0]+"~"+args[2]
		fromStr := rw.read(state, fromKey)
		bal, err := parseInt(fromStr)
		if err != nil {
			bal = 0 // zero balance = empty key
		}
		if bal < amt {
			return fmt.Errorf("insufficient balance: have %d need %d (double-spend stopped at endorsement)", bal, amt)
		}
		toStr := rw.read(state, toKey)
		toBal, err := parseInt(toStr)
		if err != nil {
			toBal = 0
		}
		rw.write(fromKey, fmt.Sprint(bal-amt))
		rw.write(toKey, fmt.Sprint(toBal+amt))
	case "DistributeYield": // args: assetId, amountINR
		if len(args) < 2 {
			return fmt.Errorf("DistributeYield needs assetId, amountINR")
		}
		if _, err := parseInt(args[1]); err != nil {
			return err
		}
		rw.read(state, "property~"+args[0])
		rw.write("yield~"+args[0]+"~"+fmt.Sprint(time.Now().UnixNano()), args[1])
	case "FreezeProperty": // args: assetId
		if len(args) < 1 {
			return fmt.Errorf("FreezeProperty needs assetId")
		}
		rw.read(state, "property~"+args[0])
		rw.write("property~"+args[0], "FROZEN")
	default:
		return fmt.Errorf("unknown chaincode function %q", fn)
	}
	return nil
}

// ---------- Lite Peer (LP) ----------

// PrivateRef locates one private-data entry in the transient store.
type PrivateRef struct {
	Org string `json:"org"`
	Key string `json:"key"`
}

// LitePeer is the stateless endorsing peer: executes chaincode, generates the
// RW set, writes private data into the transient store. No local ledger.
type LitePeer struct {
	State     *StateDB        // read-only view during simulation
	Transient *TransientStore // KeyDB hand-off to the CP
}

// Endorse executes chaincode and returns the signed proposal, RW set,
// endorsements and the transient-store references for the private data.
func (lp *LitePeer) Endorse(fn string, args []string, private map[string]map[string][]byte) (proposal string, rw *RWSet, endorsements []Endorsement, refs []PrivateRef, privateDigest string, err error) {
	rw = &RWSet{Reads: map[string]uint64{}, Writes: map[string]string{}}
	if err = simulateChaincode(lp.State, fn, args, rw); err != nil {
		return "", nil, nil, nil, "", err
	}

	// Private data → transient store (KeyDB). The proposal carries only the
	// hash of the private payload (Fabric collection-hash semantics).
	ph := sha512.New()
	orgs := make([]string, 0, len(private))
	for org := range private {
		orgs = append(orgs, org)
	}
	sort.Strings(orgs)
	for _, org := range orgs {
		fields := make([]string, 0, len(private[org]))
		field := map[string][]byte{}
		for f, v := range private[org] {
			fields = append(fields, f)
			field[f] = v
		}
		sort.Strings(fields)
		for _, f := range fields {
			key := "pv|" + org + "|" + fn + "|" + f
			lp.Transient.Put(org, key, private[org][f])
			refs = append(refs, PrivateRef{Org: org, Key: key})
			fmt.Fprintf(ph, "%s|%s|%s;", org, key, private[org][f])
		}
	}
	privateDigest = hex.EncodeToString(ph.Sum(nil))

	// proposal = channel|chaincode|fn|args|rwDigest|privateDigest
	proposal = strings.Join([]string{Channel, ChaincodeName, fn, strings.Join(args, "\x1f"), rw.Digest(), privateDigest}, "|")
	for _, msp := range policyFor(fn).RequiredMSPs {
		endorsements = append(endorsements, Endorsement{MSP: msp, Peer: msp + ".peer", Signature: signProposal(msp, proposal)})
	}
	return proposal, rw, endorsements, refs, privateDigest, nil
}

// ---------- Orderer (RAFT, simulated) ----------

// Orderer orders endorsed envelopes. Real Drunix runs Raft; this simulation
// elects a deterministic leader and stamps cluster-unique sequence numbers.
type Orderer struct {
	Nodes int
	Seq   uint64
}

// NewOrderer creates a cluster of n orderers.
func NewOrderer(n int) *Orderer { return &Orderer{Nodes: n} }

// Leader returns the current Raft leader (1-based).
func (o *Orderer) Leader() int { return int(((o.Seq + uint64(o.Nodes) - 1) % uint64(o.Nodes)) + 1) }

// Order stamps the envelope with the next sequence under the current leader.
func (o *Orderer) Order() (seq uint64, leader int) {
	o.Seq++
	return o.Seq, o.Leader()
}

// ---------- Validation Service (VS / VSCC) ----------

// ValidationService is stateless and horizontally scalable: endorsement-policy
// acceptance checks + cryptographic signature verification.
type ValidationService struct{}

// Validate returns nil when the endorsement set satisfies the policy.
func (vs *ValidationService) Validate(fn, proposal string, endorsements []Endorsement) error {
	if ok, reason := policyFor(fn).SatisfiedBy(proposal, endorsements); !ok {
		return fmt.Errorf("VSCC: %s", reason)
	}
	return nil
}

// ---------- Committing Peer (CP) ----------

// CommitResult reports one pipeline run stage by stage (judge-readable).
type CommitResult struct {
	TxID          string   `json:"txId"`
	Fn            string   `json:"fn"`
	Committed     bool     `json:"committed"`
	BlockHeight   int64    `json:"blockHeight,omitempty"`
	Stage         string   `json:"stage"` // where the tx ended: lite-peer | validation-service | committing-peer-mvcc | committed
	Reason        string   `json:"reason,omitempty"`
	OrdererLeader int      `json:"ordererLeader"`
	Seq           uint64   `json:"seq"`
	RWDigest      string   `json:"rwDigest"`
	PrivateHash   string   `json:"privateHash,omitempty"`
	EndorsedBy    []string `json:"endorsedBy"`
	DurationMs    int64    `json:"durationMs"`
}

// CommittingPeer performs MVCC validation, verifies the private-data hash from
// the transient store, applies the write set to the State DB and commits.
type CommittingPeer struct {
	State     *StateDB
	Transient *TransientStore
	Ledger    *DrunixChain
}

// mvccValidate: every key read during simulation must still sit at the same version.
func (cp *CommittingPeer) mvccValidate(rw *RWSet) (bool, string) {
	for _, k := range rw.ReadsOrder {
		cur := cp.State.GetVersion(k).Version
		if rw.Reads[k] != cur {
			return false, fmt.Sprintf("MVCC READ_CONFLICT on %s: simulated version %d, current version %d. Resubmit with fresh state.", k, rw.Reads[k], cur)
		}
	}
	return true, ""
}

// Commit runs VS → MVCC → private-data apply → state apply → ledger append.
func (cp *CommittingPeer) Commit(fn string, args []string, proposal string, rw *RWSet, endorsements []Endorsement, refs []PrivateRef, privateDigest string, leader, seq uint64) CommitResult {
	start := time.Now()
	txID := mockTxID(Channel, ChaincodeName, fn, args, seq)
	res := CommitResult{TxID: txID, Fn: fn, OrdererLeader: int(leader), Seq: seq, RWDigest: rw.Digest(), PrivateHash: privateDigest}
	for _, e := range endorsements {
		res.EndorsedBy = append(res.EndorsedBy, e.MSP)
	}

	// 1) VSCC: endorsement policy acceptance + signature verification
	vs := &ValidationService{}
	if err := vs.Validate(fn, proposal, endorsements); err != nil {
		res.Stage, res.Reason = "validation-service", err.Error()
		return res
	}

	// 2) MVCC: simulated read versions must match current state versions
	if ok, reason := cp.mvccValidate(rw); !ok {
		res.Stage, res.Reason = "committing-peer-mvcc", reason
		return res
	}

	// 3) Private data: pull from the transient store, verify the hash matches
	//    the one in the signed proposal, record only the hash in the block.
	ph := sha512.New()
	for _, ref := range refs {
		val, ok := cp.Transient.Take(ref.Org, ref.Key)
		if !ok {
			res.Stage, res.Reason = "committing-peer-private", fmt.Sprintf("private data %s (org %s) missing from transient store", ref.Key, ref.Org)
			return res
		}
		fmt.Fprintf(ph, "%s|%s|%s;", ref.Org, ref.Key, val)
	}
	if len(refs) > 0 && hex.EncodeToString(ph.Sum(nil)) != privateDigest {
		res.Stage, res.Reason = "committing-peer-private", "private data hash mismatch against endorsed proposal"
		return res
	}

	// 4) Apply the write set to the State DB (versions bump)
	cp.State.Apply(rw.Writes)

	// 5) Commit the block to the hash-chained ledger
	blk := cp.Ledger.Append("TX_COMMITTED", []map[string]interface{}{{
		"kind":       "pipeline",
		"txId":       txID,
		"chaincode":  ChaincodeName,
		"fn":         fn,
		"args":       args,
		"rwDigest":   rw.Digest(),
		"endorsedBy": res.EndorsedBy,
		"orderer":    fmt.Sprintf("raft-leader-%d-of-%d", leader, 3),
		"mvcc":       "validated",
		"vscc":       "policy-accepted",
	}})
	res.BlockHeight = blk.Height
	res.Committed = true
	res.Stage = "committed"
	res.DurationMs = time.Since(start).Milliseconds()
	return res
}

// ---------- Pipeline: Client → DLT-Gateway → LP → Orderer → VS → CP ----------

// Pipeline is the full Drunix transaction path, wired once and reused.
type Pipeline struct {
	LP    *LitePeer
	Order *Orderer
	CP    *CommittingPeer
	mu    sync.Mutex // serializes simulation/commit on the single-channel demo
}

// NewPipeline wires the components over shared state, transient store and ledger.
func NewPipeline(state *StateDB, transient *TransientStore, ledger *DrunixChain) *Pipeline {
	return &Pipeline{
		LP:    &LitePeer{State: state, Transient: transient},
		Order: NewOrderer(3),
		CP:    &CommittingPeer{State: state, Transient: transient, Ledger: ledger},
	}
}

// Submit runs the full lifecycle: endorse (LP) → order (RAFT) → validate (VS)
// → MVCC + commit (CP). privateData maps org → field → value and travels only
// through the transient store.
func (p *Pipeline) Submit(fn string, args []string, private map[string]map[string][]byte) (CommitResult, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	proposal, rw, endorsements, refs, privateDigest, err := p.LP.Endorse(fn, args, private)
	if err != nil {
		return CommitResult{Fn: fn, Stage: "lite-peer", Reason: err.Error()}, err
	}
	seq, leader := p.Order.Order()
	res := p.CP.Commit(fn, args, proposal, rw, endorsements, refs, privateDigest, uint64(leader), seq)
	if !res.Committed {
		return res, fmt.Errorf("%s: %s", res.Stage, res.Reason)
	}
	return res, nil
}
